### ISSUE TITLE
Styleguide erstellen

### ISSUE THREAD

**Issue by slinssen** [wahlgenial/wahlgenial-webapp#2]
Aufbauend auf den bestehenden Styleguide (https://scene.zeplin.io/project/5a04143d4ea5fff0b83cd265) sollte ein weiterer erstellt werden, um den NutzerInnen deutlich zu machen, dass die Zielgruppe der Wahlapps für Lehrer Seite eine andere ist, als auf den anderen Seiten.
(Kein Anspruch auf Vollständigkeit des Tickets. Kann also gerne ergänzt werden)

**Comment by johannesnolte** [comment]
Erste wichtige UI Sketches fertig: https://github.com/johannesnolte/wahlgenial/wiki/P2-UI-Sketching

**Comment by johannesnolte** [comment]
Weitere UI Sketches sind fertig: https://github.com/johannesnolte/wahlgenial/wiki/P2-UI-Sketching
