### ISSUE TITLE
Architektur und Datenmodellierung

### ISSUE THREAD

**Issue by nawo1107** [wahlgenial/wahlgenial-webapp#23]

**Comment by slinssen** [comment]
F17: W sollte dem Stakeholder die Möglichkeit bieten, die Suchergebnisse durch die
Filterfunktionen (Stufe, Stichwort, Suchbegriff, Geräte, Unterrichtsfach) filtern zu
lassen.

**Comment by slinssen** [comment]
Datenstrukturen für die teacher_app und teacher_app_tag system wurden erstellt. Das Tag system muss noch weitgehend implementiert werden. Ich würde daran arbeiten, sobald ein paar Beispieldatensätze stehen. Eröffne hier für noch ein Ticket.
