### ISSUE TITLE
Content einpflegen

### ISSUE THREAD

**Issue by nawo1107** [wahlgenial/wahlgenial-webapp#25]
Übertragung der Inhalte in Datenbank

Natalie und Johannes: Übertragung der Inhalte in CSV Dokument
Cathrin und Sven: Import der CSV Datei in die Datenbank

**Comment by johannesnolte** [comment]
Inhalte fürs SoSe19 fertig, muss nur noch importiert werden.

**Comment by johannesnolte** [comment]
Doen
