### ISSUE TITLE
Content einpflegen Über-Uns-Seite

### ISSUE THREAD

**Issue by nawo1107** [wahlgenial/wahlgenial-webapp#27]

**Comment by johannesnolte** [comment]
"Über uns" Seite besteht bereits auf http://www.wahldatenhelfer.de/. Muss also nur noch inhaltlich angepasst werden.

**Comment by johannesnolte** [comment]
Hier der neue Text. Scheint hard gecodet zu sein, muss also manuell reinkopiert werden, nicht übers Admin-Panel. Aber am besten erst, wenn das Lehrermodul auch wirklich online ist.

Fett markierte Textpassagen sind neu:

Über uns

Unser Ziel
Wir möchten dir die Wahl erleichtern! Die Entscheidung zu fällen, welche Partei man wählen soll, ist gar nicht so leicht! Dabei gibt es jedoch so einige Angebote, die sich eben diesem Problem widmen. Wir möchten dir die Möglichkeit geben, dich über Parteien und ihre Programme zu informieren. Durch deine Wahl kannst du deine Zukunft mit gestalten!

Also schau dich doch einfach bei unseren Wahl-Apps um, und entscheide du, wie duch dich informieren möchtest!

*Seit Anfang 2020 bieten wir zudem eine Unterseite extra für Lehrerinnen und Lehrer an. Dort findest du zur Vorbereitung deines Unterrichts spannende und nützlich Webangebote rund um die Themen Wahlen und Politik. Die Angebote wurden von uns auf Qualität geprüft. Setze sie im Unterricht ein und gebe deinen Schülerinnen und Schülern einen modernen, interaktiven Zugang zu politischer Bildung.* 

Wer wir sind?
Tatjana Lajendäcker
Tatjana Lajendäcker hat in Köln moderne China Studien und BWL studiert und arbeitet seit 2010 bei Railslove als Projekt- und Backoffice-Managerin. Außerdem ist sie Mitgründerin von Coworking Cologne und Co-Organisator von Railsgirls Cologne&Rheinland.

Jan Kus
Jan Kus ist Mitgründer der Unternehmen Railslove und hack.institute. Seine Leidenschaft gilt dem Aufbau von Netzwerken und der Vermittlung zwischen den kontrastierenden Welten großer Unternehmen und der Community – um an dieser Schnittstelle perfekte digitale Produkte und Erlebnisse zu formen.
Jan entwickelt schon seit 2007 professionell Webapplikationen (vornehmlich mit Ruby on Rails) und ist seit 2010 Open Data Fan. 2012 hat er die KölnAPI Usergroup ins Leben gerufen die heute das OKLab ist. Seit 2013 konzentrieren sich seine Open Data Aktiväten auf dem Thema Wahlen. Neben dem Wahl.Daten.Helfer-Hackathon und der App hat er u.a. den Wahllokalfinder auf Basis von Open Data Programmiert.
Mit hack.institute organisiert Jan auch viele Events rund um das Thema Open Data, wie z.B.: die Mitorganisation der Wahlsalons und den Internationalen Open Data Day in Köln.

*Studentisches Team*
*Von Herbst 2018 bis Frühjahr 2020 wurde Wahlgenial als Projekt im Master-Studiengang Medieninformatik an der TH Köln weiterentwickelt. Das Projektteam besteht aus Sven Linßen, Johannes Nolte, Cathrin Pape und Natalie Wolf aus den Studien-Schwerpunkten "Multi Perspective Product Development" und "Social Computing". Im ersten Semester wurde der zuvor noch nicht vorhandene Lehrerbereich konzipiert, welcher im zweiten Semester programmiert und mit Inhalten gefüllt wurde. Im dritten Semester erfolgte die Verschmelzung mit der zuvor bereits bestehenden Wahlgenial-Seite und die Aktualisierung dieser. Betreut wurde das Projekt von Prof. Dr. Kristian Fischer und Jan Kus. Beim Medieninformatik Showcase des Advanced Media Institutes an der TH Köln wurde das Projekt im Dezember 2019 als eines der besten im Studienjahr 2019 ausgezeichnet.*

Wie ist das Projekt entstanden?

Die ganze Idee begann mit einem Hackathon zur Bundestagswahl 2013, dort haben wir den Wahl-Daten-Helfer ins Leben gerufen. Seit dem hat sich viel getan: Aus dem Event "Wahl.Daten.Helfer" ist eine Plattform geworden, der jungen Menschen *und ihren LehrerInnen* ein Informationsangebot rund ums Thema Wahlen und Politik liefern und ihnen die Entscheidung bei den nächsten Wahlen erleichtern soll.

Ein paar Einblicke vom Event von 2013 findet ihr hier:


Wahlbeteiligung
bei den Bundestagswahlen 2017
69,9%
18-20 Jährige
67%
21-24 Jährige

**Comment by Cathrin94** [comment]
eingepflegt und online
