### ISSUE TITLE
Anforderungen aus Konzept 1 in die Issues übertragen

### ISSUE THREAD

**Issue by slinssen** [wahlgenial/wahlgenial-webapp#33]
Anforderungen aus Konzept 1 (https://github.com/johannesnolte/wahlgenial/blob/master/Konzept_Projekt1.pdf) in die jeweiligen Issues kommentieren o.ä.

z.b.: "F17: W sollte dem Stakeholder die Möglichkeit bieten, die Suchergebnisse durch die
Filterfunktionen (Stufe, Stichwort, Suchbegriff, Geräte, Unterrichtsfach) filtern zu
lassen." zu Architektur und Datenmodellierung #23

**Comment by slinssen** [comment]
bei Bedarf auch neue Issues erstellen

**Comment by slinssen** [comment]
sollte ja soweit gemacht sein? Kann man das Ticket schließen?

**Comment by johannesnolte** [comment]
Ja
