### ISSUE TITLE
teacher_apps Liste/Datenstruktur der Lehrer-Apps Detailseiten sollte um weitere Attribute ergänzt werden

### ISSUE THREAD

**Issue by slinssen** [wahlgenial/wahlgenial-webapp#35]
teasertext: string
published: boolean
external_link: string
logo/picture: string

**Comment by slinssen** [comment]
published wurde ergänzt

**Comment by slinssen** [comment]
Die Erweiterung der Datenstruktur der Detailseite sollte auch in die Dokumentation übernommen werden. Ich mache gleich noch einen Screenshot von der (vll vorerst) fertigen Datenbank.

**Comment by slinssen** [comment]
![image](https://user-images.githubusercontent.com/5626201/62291568-8f92c280-b464-11e9-8cf6-5052b9fedcda.png)

**Comment by johannesnolte** [comment]
Noch offen: In Wiki diese Struktur dokumentieren.

**Comment by johannesnolte** [comment]
In Wiki dokumentiert: https://github.com/johannesnolte/wahlgenial/wiki/Prozessdoku-P2
