### ISSUE TITLE
A01 Backend vorhanden

### ISSUE THREAD

**Issue by nawo1107** [wahlgenial/wahlgenial-webapp#37]
W muss RedakteurInnen und AdministratorInnnen die Möglichkeit bieten, sich in das System Backend einzuloggen.

**Comment by nawo1107** [comment]
W muss RedakteurInnen und AdministratorInnnen die Möglichkeit bieten, sich in das System Backend einzuloggen.

**Comment by slinssen** [comment]
das Issue ist leider nicht ganz deutlich? Ins Backend einloggen? Vielleicht bearbeiten wir das nochmal...

**Comment by slinssen** [comment]
Ist hier vielleicht gemeint, dass W RedakteurInnen und AdministratorInnnen die Möglichkeit bieten sich in ein Login-Bereich einzuloggen?
Wenn ja, sollten wir klären wie dieser aussehen könnte. Die Funktionen sind ja größtenteils beschrieben, aber die Aufmachung der Seite ist sehr unkonkret.

**Comment by johannesnolte** [comment]
Prio auf Low da sehr umfangreich und nicht zwingend für betrieb am Anfang nötig -> schlechtes Kosten-Nutzen Verhältnis.

**Comment by slinssen** [comment]
Es besteht bereits ein Adminportal.
