### ISSUE TITLE
A02 Redakteurs-Login (nicht nur Admin-Zugang)

### ISSUE THREAD

**Issue by nawo1107** [wahlgenial/wahlgenial-webapp#38]
W muss RedakteurInnen (außer AdministratorInnen) die Möglichkeit bieten, sich nach Zustimmung eines/einer Administrators/Administratorin zu registrieren und sich dann anmelden zu können.

**Comment by johannesnolte** [comment]
Prio auf Low da das Backend insgesamt heruntergestuft wurde (https://github.com/wahlgenial/wahlgenial-webapp/issues/37)
