### ISSUE TITLE
Bessere Feedbackmöglichkeit (Inhalte einreichen)

### ISSUE THREAD

**Issue by nawo1107** [wahlgenial/wahlgenial-webapp#42]
Benutzer sollen Feedback und Vorschläge für Inhalte an den Admin übermitteln können.

**Comment by slinssen** [comment]
Ist quasi schon gegeben oder? http://www.wahlgenial.de/ueber-uns
Hier sollte noch besprochen werden, wie eine Neuerung aussehen könnte, wenn nötig.

**Comment by johannesnolte** [comment]
Ich kann mir schon vorstellen, dass man das noch besser machen kann. Würde ich aber dann auch Prio Low setzten. Erst mal angebot ans Laufen kriegen und dann solche Funktionen nachziehen.

**Comment by slinssen** [comment]
ist soweit gegeben über email. Eine Implementierung wurde zunächst verworfen
