### ISSUE TITLE
A04 Kommentare löschen

### ISSUE THREAD

**Issue by nawo1107** [wahlgenial/wahlgenial-webapp#43]
Falls ein/e AdministratorIn oder RedakteurIn eingeloggt ist, muss W es ihnen ermöglichen, Kommentare auf der Detailseite eines Tools zu löschen.

**Comment by johannesnolte** [comment]
Macht nur mit backend insgesamt sinn (löschen über DB geht ja schon), daher erstmal wie Backend selbst auf niedrig gestuft. Und: Bisher sind ja noch gar keine Kommentare möglich. https://github.com/wahlgenial/wahlgenial-webapp/issues/37

**Comment by slinssen** [comment]
wurde vorerst verworfen
