### ISSUE TITLE
A07 Neue Einträge

### ISSUE THREAD

**Issue by nawo1107** [wahlgenial/wahlgenial-webapp#44]
Falls ein/e RedakteurIn/AdministratorIn eingeloggt ist, muss W es ihnen ermöglichen, ein neues Tool mit einer Beschreibung im passendem Text Format und einem Bild in passender Größe im Backend hinzuzufügen.

**Comment by johannesnolte** [comment]
Möglich (über Datenbank via Postgres /postico bzw. CSV Import damit).
