### ISSUE TITLE
A11 Redakteure löschen

### ISSUE THREAD

**Issue by nawo1107** [wahlgenial/wahlgenial-webapp#48]
Falls ein/e AdministratorIn eingeloggt ist, muss W es ermöglichen, Benutzerkonten löschen zu können.

**Comment by johannesnolte** [comment]
Macht nur mit Backend Sinn (löschen über DB geht ja schon), daher erstmal wie Backend selbst auf niedrig gestuft.

**Comment by slinssen** [comment]
Funktion wurde aufgrund von zu wenig Zeit vorerst verworfen.
