### ISSUE TITLE
A03 Kommentare durch Nutzer

### ISSUE THREAD

**Issue by nawo1107** [wahlgenial/wahlgenial-webapp#57]
Besuchern der Webseite muss W es ermöglichen, Kommentare auf der Detailseite eines Tools hinzuzufügen.

**Comment by slinssen** [comment]
Designvorschlag, sollte nochmal gegengecheckt werden:

![68747470733a2f2f7777772e6a6f68616e6e65736e6f6c74652e64652f66696c65732f74686b6f656c6e2f7761686c67656e69616c2f75695f32303139303930335f362e4a5047 (1)](https://user-images.githubusercontent.com/5626201/70525631-13159c00-1b48-11ea-8ed0-2a8da65c41ba.jpeg)

**Comment by slinssen** [comment]
wurde vorerst nach hinten gestellt
