### ISSUE TITLE
A17 Favicon

### ISSUE THREAD

**Issue by nawo1107** [wahlgenial/wahlgenial-webapp#58]
W sollte Favicon auf der Plattform haben.

**Comment by slinssen** [comment]
fehlt nur noch auf der noch zu erstellenden Detailseite

**Comment by slinssen** [comment]
wird wahrscheinlich von der Originalseite gegeben sein. Würde das Ticket vorerst zurückweisen.

**Comment by johannesnolte** [comment]
Dann schließen wir es.
