### ISSUE TITLE
 A14b Filterfunktion Advanced

### ISSUE THREAD

**Issue by johannesnolte** [wahlgenial/wahlgenial-webapp#63]
W sollte dem Stakeholder die Möglichkeit bieten, die Suchergebnisse durch die Filterfunktionen neben Stufe und  Suchbegriff auch nach Geräte und Unterrichtsfach ﬁltern zu lassen.

**Comment by slinssen** [comment]
Designvorschlag, der mit Sabine abgeglichen werden sollte:

![68747470733a2f2f7777772e6a6f68616e6e65736e6f6c74652e64652f66696c65732f74686b6f656c6e2f7761686c67656e69616c2f75695f32303139303930335f332e4a5047](https://user-images.githubusercontent.com/5626201/70525545-e5c8ee00-1b47-11ea-8d5c-21b76bd7ac84.jpeg)

**Comment by johannesnolte** [comment]
Im Designvorschlag fehlen übrigens noch die Geräte

**Comment by Cathrin94** [comment]
Neues Design. Bis auf den Kategorienfilter funktioniert alles.

![Screenshot 2020-03-13 at 12 52 30](https://user-images.githubusercontent.com/22667062/76618754-9b318600-6529-11ea-920c-18739acb3c12.png)
