### ISSUE TITLE
A16b Detailseite füllen

### ISSUE THREAD

**Issue by johannesnolte** [wahlgenial/wahlgenial-webapp#64]
Die Detailseite aus Issue A16a soll mit dem Bild, der Beschreibung, den Links, den Kommentaren und den Bewertungen zum jeweiligen Eintrag gefüllt werden.

**Comment by johannesnolte** [comment]
Siehe auch Vorgänger-Issue: https://github.com/wahlgenial/wahlgenial-webapp/issues/52

**Comment by johannesnolte** [comment]
https://github.com/wahlgenial/wahlgenial-webapp/issues/52

**Comment by slinssen** [comment]
Hier ein paar Bilder als Designvorschlag. Man sollte hier noch mit Sabine besprechen wie das ganze im Detail aussehen könnte. Ich glaube jedoch, dass die Bilder zumindest um mit dem coden anzufangen ausreichen sollten.
![68747470733a2f2f7777772e6a6f68616e6e65736e6f6c74652e64652f66696c65732f74686b6f656c6e2f7761686c67656e69616c2f75695f32303139303930335f362e4a5047](https://user-images.githubusercontent.com/5626201/70525398-8d91ec00-1b47-11ea-9b15-236b68e94e46.jpeg)
![68747470733a2f2f7777772e6a6f68616e6e65736e6f6c74652e64652f66696c65732f74686b6f656c6e2f7761686c67656e69616c2f75695f32303139303930335f352e4a5047](https://user-images.githubusercontent.com/5626201/70525400-8f5baf80-1b47-11ea-993e-5762d596f082.jpeg)
![68747470733a2f2f7777772e6a6f68616e6e65736e6f6c74652e64652f66696c65732f74686b6f656c6e2f7761686c67656e69616c2f75695f32303139303930335f342e4a5047](https://user-images.githubusercontent.com/5626201/70525401-908cdc80-1b47-11ea-908b-7bdb9f8478a7.jpeg)

**Comment by Cathrin94** [comment]
Neues Design wurde bereits umgesetzt

<img width="872" alt="AppDetail_aktuell" src="https://user-images.githubusercontent.com/22667062/78008674-3d31da80-7340-11ea-8467-5b408063020c.png">
