### ISSUE TITLE
Teacher_apps und election_apps_apps zusammenführen?

### ISSUE THREAD

**Issue by slinssen** [wahlgenial/wahlgenial-webapp#67]
Es sollte mit Timo besprochen werden, ob es Sinn macht die beiden Datenbanktabellen zusammenzuführen.

![Bildschirmfoto 2019-12-09 um 10 38 55](https://user-images.githubusercontent.com/5626201/70424777-3a009f00-1a70-11ea-996c-e5df14881e79.png)
![Bildschirmfoto 2019-12-09 um 10 38 36](https://user-images.githubusercontent.com/5626201/70424779-3a009f00-1a70-11ea-8b0a-f0e007177fd7.png)

**Comment by johannesnolte** [comment]
Wenn es getrennte Tabellen bleiben: Bitte beachten, dass in teacher_apps noch ein datenfeld für die Kategorie fehlt.

**Comment by slinssen** [comment]
Die Idee des zusammenführen wurde verworfen
