### ISSUE TITLE
Wahl-Termine dynamisch machen? Oder redaktionell überarbeiten?

### ISSUE THREAD

**Issue by slinssen** [wahlgenial/wahlgenial-webapp#68]
Vielleicht gibt es hier eine api o.ä. auf die man zugreifen könnte, sodass man die Seite nicht selbst pflegen muss?

**Comment by johannesnolte** [comment]
Evt. hier rausziehen? https://de.wikipedia.org/wiki/Liste_voraussichtlicher_Wahltermine_in_Deutschland

**Comment by johannesnolte** [comment]
Oder hier rausziehen (Primärquelle für Wikipedia): https://www.bundeswahlleiter.de/service/wahltermine.html
Oder hier her: http://www.wahlrecht.de/termine.htm

**Comment by johannesnolte** [comment]
Erstmal wahrscheinlich manuell eintragen. Kann direkt im Admin Panel gemacht werden. Gerne du heute Nachmittag, @nawo1107.

**Comment by nawo1107** [comment]
Momentan gibt es nur für drei Wahlen nächstes Jahr die genauen Daten. Wäre gut wenn im Admin Panel das Datum kein Pflichttermin mehr wäre und man dann einfach "Frühjahr 2021" eintragen könnte. Sonst sieht das bisschen komisch aus wenn nur drei Wahlen eingetragen sind

**Comment by nawo1107** [comment]
Die Darstellung ist irgendwie kaputt und sollte vielleicht nochmal überarbeitet werden. Die Tabelle breitet sich nicht auf das komplette weiße Feld aus

**Comment by slinssen** [comment]
Der Aufwand das Ticket umzusetzen wurde als unverhältnismäßig eingestuft, da die Pflege der Termine einmal im Jahr stattfinden kann und schnell gemacht ist.
