### ISSUE TITLE
"Wen soll ich wählen?" redaktionell überarbeiten

### ISSUE THREAD

**Issue by slinssen** [wahlgenial/wahlgenial-webapp#70]
Auf einen neuen Stand bringen. Evtl. mit Parteiprogrammen

**Comment by slinssen** [comment]
"i"- Punkt Karte sollte dementsprechend angepasst werden

**Comment by johannesnolte** [comment]
Ich finde das ist Prio Mittel, muss allerdings nicht am 17./18. passieren.

**Comment by nawo1107** [comment]
- https://www.afd.de/grundsatzprogramm/
- die-linke.de/themen/wohnen/
- https://www.gruene.de/themen
- https://www.fdp.de/sites/default/files/uploads/2017/08/07/20170807-wahlprogramm-wp-2017-v16.pdf
-https://www.spd.de/fileadmin/Dokumente/Beschluesse/Grundsatzprogramme/hamburger_programm.pdf
- https://www.cdu.de/system/tdf/media/dokumente/071203-beschluss-grundsatzprogramm-6-navigierbar.pdf?file=1
