### ISSUE TITLE
Design überarbeiten

### ISSUE THREAD

**Issue by johannesnolte** [wahlgenial/wahlgenial-webapp#76]
Sabine erstellt neue Screens für die Detail- und die Filterseite sowie einen Hinweis auf der Startseite

**Comment by Cathrin94** [comment]
Von Sabine überarbeitete Screens sind in Abstract zu finden unter: 
https://app.abstract.com/projects/4d4ec2a3-1e19-437f-92ac-a387332fc413/branches/master/files/65a2e4e7-bb17-486b-9af1-2c8a374e6964/pages/DDA7CE6F-825A-4F0F-ADC5-14678569EC19

![Screenshot 2020-03-13 at 12 47 15](https://user-images.githubusercontent.com/22667062/76618544-1b0b2080-6529-11ea-96ab-1c0698954ee4.png)
![Screenshot 2020-03-13 at 12 47 49](https://user-images.githubusercontent.com/22667062/76618548-1cd4e400-6529-11ea-93a4-228d8ea48bd9.png)
